### PR TITLE
Fix missing hass as parameter issue since HA 2022.2

### LINKED ISSUE #11: [BUG] brematic does not work anymore after upgrade to home assistant 2022.2
**Describe the bug**
After the update of Home Assistant to 2022.2, hass-brematic does not work anymore. When starting home assistant, the log says

`Logger: homeassistant.components.switch
Source: custom_components/brematic/switch.py:173
Integration: Schalter ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 10:05:32 (1 occurrences)
Last logged: 10:05:32
Error while setting up brematic platform for switch

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/brematic/switch.py", line 151, in setup_platform
    BrematicSwitch(
  File "/config/custom_components/brematic/switch.py", line 173, in __init__
    super().__init__()
TypeError: __init__() missing 1 required positional argument: 'hass'`

It seems to fail to initialize my switches that I have set up in the configuration with brematic:
`
switch:
  - platform: brematic
    host: '192.168.178.21'
    system_code: '11111'
    gateway_type: 'Brennenstuhl'
    switches:
      lamp_tolomeo:
        unit_code: '00010'
        unit_type: 'AB440SA'
        friendly_name: Lampe TV
`

With 2021.12 that issue did not occur.

**To Reproduce**
Update HA to 2022.2

**Expected behavior**

**Home Assistant:**
 - Home Assistant Version: 2022.2
 - Brematic Component Version: 0.5.0

### PR DESCRIPTION
**Pull request by TheZoker**
I think this should fix #11 (at least it works in my HA instance)

### CODE REVIEW

**Review by shawly — APPROVED** [review]
I can confirm that this works!

**Comment by TheZoker** [comment]
@tefinger Can you maybe have a look at this small PR? Thanks :)

**Comment by tefinger** [comment]
Thx for submitting the PR. I merged it and will add it to a new release.

Sorry for the delay. Somehow I missed the PR.
