### PR TITLE
Fix "Error while setting up brematic platform for switch"

### PR DESCRIPTION
**Pull request by TheZoker**
Since the update to 2025.8.x beta I had this issue in my logs and the integration was not working anymore:
```
2025-08-02 17:57:59.983 ERROR (MainThread) [homeassistant.components.switch] Error while setting up brematic platform for switch: TemplateEntity.__init__() missing 2 required positional arguments: 'config' and 'unique_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/brematic/switch.py", line 151, in setup_platform
    BrematicSwitch(
    ~~~~~~~~~~~~~~^
        hass,
        ^^^^^
    ...<4 lines>...
        state_template,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/brematic/switch.py", line 173, in __init__
    super().__init__(hass)
    ~~~~~~~~~~~~~~~~^^^^^^
TypeError: TemplateEntity.__init__() missing 2 required positional arguments: 'config' and 'unique_id'
```

This PR should fix this issue (at least it fixed it for me)

### CODE REVIEW

**Comment by wolf-chris** [comment]
@TheZoker : Thank you very much !

**Comment by TheZoker** [comment]
@tefinger Can you please have a look at this PR and maybe merge it?
If you look at the referenced issue, this seems to fix the issue for most people
