### ISSUE TITLE

Entität nicht gefunden


### ISSUE THREAD

**Issue by mopro1985** [tefinger/hass-brematic#18]
"Entität nicht gefunden."

Logger: homeassistant.components.switch
Quelle: helpers/entity_platform.py:451
Integration: Schalter (Dokumentation, Probleme)
Erstmals aufgetreten: 00:02:28 (1 Vorkommnis)
Zuletzt protokolliert: 00:02:28

Error while setting up brematic platform for switch: TemplateEntity.__init__() missing 2 required positional arguments: 'config' and 'unique_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/brematic/switch.py", line 151, in setup_platform
    BrematicSwitch(
    ~~~~~~~~~~~~~~^
        hass,
        ^^^^^
    ...<4 lines>...
        state_template,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/brematic/switch.py", line 173, in __init__
    super().__init__(hass)
    ~~~~~~~~~~~~~~~~^^^^^^
TypeError: TemplateEntity.__init__() missing 2 required positional arguments: 'config' and 'unique_id'



Home Assistant:
Core 2025.8.0
Supervisor 2025.07.3
Operating System 16.0
Frontend 20250806.0

Brematic Component Version 0.7.1

**Comment by paulbrause** [comment]
Same problem here after updating Home Assistant to 2025.8.0.

**Comment by Cobol390** [comment]
Same problem here after updating Home Assistant to 2025.8.0.

**Comment by paulbrause** [comment]
This PR fixed it for me:
[https://github.com/tefinger/hass-brematic/pull/17](https://github.com/tefinger/hass-brematic/pull/17)

**Comment by mopro1985** [comment]
> This PR fixed it for me:
> [https://github.com/tefinger/hass-brematic/pull/17](https://github.com/tefinger/hass-brematic/pull/17)

Right!

**Comment by ishiprog** [comment]
> This PR fixed it for me: [#17](https://github.com/tefinger/hass-brematic/pull/17)

Absolutely!

**Comment by Cobol390** [comment]
#17 Did it for me as well…
Glad that these old brennenstuhl switches still work and I could save some ressources of old mother earth 😳
